language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
services:
  - docker
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features tls
before_install:
  - docker pull contribsys/faktory:latest
  - docker run -d -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:latest /faktory -b :7419 -w :7420
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --out Xml --features tls --forward
    bash <(curl -s https://codecov.io/bash)
  fi
