[package]
name = "faktory"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
bufstream = "0.1"
sha2 = "0.6.0"
hostname = "0.1.3"
libc = "0.2"
rand = "0.3"
chrono = "0.4"
