[package]
name = "faktory"
version = "0.3.0"

description = "API bindings for the language-agnostic Faktory work server"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/faktory"
homepage = "https://github.com/jonhoo/faktory-rs"
repository = "https://github.com/jonhoo/faktory-rs.git"

keywords = ["faktory", "api-bindings", "work-server", "job-server"]
categories = ["api-bindings", "asynchronous", "network-programming"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/faktory-rs" }

[dependencies]
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
bufstream = "0.1"
sha2 = "0.6.0"
hostname = "0.1.3"
libc = "0.2"
rand = "0.3"
chrono = { version = "0.4", features = ["serde"] }
url = "1.5"
atomic-option = "0.1"
native-tls = "0.1.4"
