on:
  push:
    branches: [main]
  pull_request:
name: With dependencies at minimal versions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: cargo update -Zminimal-versions
        uses: actions-rs/cargo@v1
        with:
          command: update
          toolchain: nightly
          args: -Zminimal-versions
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all-targets
        env: # set this explicitly so integration tests will run
          FAKTORY_URL: tcp://127.0.0.1:7419
    services:
      faktory:
        image: contribsys/faktory:latest
        ports:
          - 7419:7419
          - 7420:7420
